# Copyright (c) 2022-2026 Nicolas ROBERT.
# Distributed under MIT license. Please see LICENSE for details.
#
# This file is generated by generator/generate.tcl, do not edit by hand.

namespace eval ::implot3d {
    # ImAxis3D_X     : X-axis
    # ImAxis3D_Y     : Y-axis
    # ImAxis3D_Z     : Z-axis
    cffi::enum define ImAxis3D_ {
        ImAxis3D_X     0
        ImAxis3D_Y     1
        ImAxis3D_Z     2
        ImAxis3D_COUNT 3
    }

    # ImPlane3D_YZ    : YZ plane (perpendicular to X-axis)
    # ImPlane3D_XZ    : XZ plane (perpendicular to Y-axis)
    # ImPlane3D_XY    : XY plane (perpendicular to Z-axis)
    cffi::enum define ImPlane3D_ {
        ImPlane3D_YZ    0
        ImPlane3D_XZ    1
        ImPlane3D_XY    2
        ImPlane3D_COUNT 3
    }

    # ImPlot3DAxisFlags_None          : Default
    # ImPlot3DAxisFlags_NoLabel       : No axis label will be displayed
    # ImPlot3DAxisFlags_NoGridLines   : No grid lines will be displayed
    # ImPlot3DAxisFlags_NoTickMarks   : No tick marks will be displayed
    # ImPlot3DAxisFlags_NoTickLabels  : No tick labels will be displayed
    # ImPlot3DAxisFlags_LockMin       : The axis minimum value will be locked when panning/zooming
    # ImPlot3DAxisFlags_LockMax       : The axis maximum value will be locked when panning/zooming
    # ImPlot3DAxisFlags_AutoFit       : Axis will be auto-fitting to data extents
    # ImPlot3DAxisFlags_Invert        : The axis will be inverted
    # ImPlot3DAxisFlags_PanStretch    : Panning in a locked or constrained state will cause the axis to stretch if possible
    cffi::enum define ImPlot3DAxisFlags_ {
        ImPlot3DAxisFlags_None          0
        ImPlot3DAxisFlags_NoLabel       1
        ImPlot3DAxisFlags_NoGridLines   2
        ImPlot3DAxisFlags_NoTickMarks   4
        ImPlot3DAxisFlags_NoTickLabels  8
        ImPlot3DAxisFlags_LockMin       16
        ImPlot3DAxisFlags_LockMax       32
        ImPlot3DAxisFlags_AutoFit       64
        ImPlot3DAxisFlags_Invert        128
        ImPlot3DAxisFlags_PanStretch    256
        ImPlot3DAxisFlags_Lock          48
        ImPlot3DAxisFlags_NoDecorations 11
    }

    # ImPlot3DCol_TitleText     : Title color
    # ImPlot3DCol_InlayText     : Color for texts appearing inside of plots
    # ImPlot3DCol_FrameBg       : Frame background color
    # ImPlot3DCol_PlotBg        : Plot area background color
    # ImPlot3DCol_PlotBorder    : Plot area border color
    # ImPlot3DCol_LegendBg      : Legend background color
    # ImPlot3DCol_LegendBorder  : Legend border color
    # ImPlot3DCol_LegendText    : Legend text color
    # ImPlot3DCol_AxisText      : Axis label and tick lables color
    # ImPlot3DCol_AxisGrid      : Axis grid color
    # ImPlot3DCol_AxisTick      : Axis tick color (defaults to AxisGrid)
    # ImPlot3DCol_AxisBg        : Background color of axis hover region (defaults to transparent)
    # ImPlot3DCol_AxisBgHovered : Axis hover color (defaults to ImGuiCol_ButtonHovered)
    # ImPlot3DCol_AxisBgActive  : Axis active color (defaults to ImGuiCol_ButtonActive)
    cffi::enum define ImPlot3DCol_ {
        ImPlot3DCol_TitleText     0
        ImPlot3DCol_InlayText     1
        ImPlot3DCol_FrameBg       2
        ImPlot3DCol_PlotBg        3
        ImPlot3DCol_PlotBorder    4
        ImPlot3DCol_LegendBg      5
        ImPlot3DCol_LegendBorder  6
        ImPlot3DCol_LegendText    7
        ImPlot3DCol_AxisText      8
        ImPlot3DCol_AxisGrid      9
        ImPlot3DCol_AxisTick      10
        ImPlot3DCol_AxisBg        11
        ImPlot3DCol_AxisBgHovered 12
        ImPlot3DCol_AxisBgActive  13
        ImPlot3DCol_COUNT         14
    }

    # ImPlot3DColormap_Deep     : Same as seaborn "deep"
    # ImPlot3DColormap_Dark     : Same as matplotlib "Set1"
    # ImPlot3DColormap_Pastel   : Same as matplotlib "Pastel1"
    # ImPlot3DColormap_Paired   : Same as matplotlib "Paired"
    # ImPlot3DColormap_Viridis  : Same as matplotlib "viridis"
    # ImPlot3DColormap_Plasma   : Same as matplotlib "plasma"
    # ImPlot3DColormap_Hot      : Same as matplotlib/MATLAB "hot"
    # ImPlot3DColormap_Cool     : Same as matplotlib/MATLAB "cool"
    # ImPlot3DColormap_Pink     : Same as matplotlib/MATLAB "pink"
    # ImPlot3DColormap_Jet      : Same as matplotlib/MATLAB "jet"
    # ImPlot3DColormap_Twilight : Same as matplotlib "twilight"
    # ImPlot3DColormap_RdBu     : Same as matplotlib "RdBu"
    # ImPlot3DColormap_BrBG     : Same as matplotlib "BrGB"
    # ImPlot3DColormap_PiYG     : Same as matplotlib "PiYG"
    # ImPlot3DColormap_Spectral : Same as matplotlib "Spectral"
    # ImPlot3DColormap_Greys    : White/black
    cffi::enum define ImPlot3DColormap_ {
        ImPlot3DColormap_Deep     0
        ImPlot3DColormap_Dark     1
        ImPlot3DColormap_Pastel   2
        ImPlot3DColormap_Paired   3
        ImPlot3DColormap_Viridis  4
        ImPlot3DColormap_Plasma   5
        ImPlot3DColormap_Hot      6
        ImPlot3DColormap_Cool     7
        ImPlot3DColormap_Pink     8
        ImPlot3DColormap_Jet      9
        ImPlot3DColormap_Twilight 10
        ImPlot3DColormap_RdBu     11
        ImPlot3DColormap_BrBG     12
        ImPlot3DColormap_PiYG     13
        ImPlot3DColormap_Spectral 14
        ImPlot3DColormap_Greys    15
    }

    # ImPlot3DCond_None   : No condition (always set the variable), same as _Always
    # ImPlot3DCond_Always : No condition (always set the variable)
    # ImPlot3DCond_Once   : Set the variable once per runtime session (only the first call will succeed)
    cffi::enum define ImPlot3DCond_ {
        ImPlot3DCond_None   0
        ImPlot3DCond_Always 1
        ImPlot3DCond_Once   2
    }

    # ImPlot3DDummyFlags_None : Default
    cffi::enum define ImPlot3DDummyFlags_ {
        ImPlot3DDummyFlags_None 0
    }

    # ImPlot3DFlags_None        : Default
    # ImPlot3DFlags_NoTitle     : Hide plot title
    # ImPlot3DFlags_NoLegend    : Hide plot legend
    # ImPlot3DFlags_NoMouseText : Hide mouse position in plot coordinates
    # ImPlot3DFlags_NoClip      : Disable 3D box clipping
    # ImPlot3DFlags_NoMenus     : The user will not be able to open context menus
    # ImPlot3DFlags_Equal       : X, Y, and Z axes will be constrained to have the same units/pixel
    # ImPlot3DFlags_NoRotate    : Lock rotation interaction
    # ImPlot3DFlags_NoPan       : Lock panning/translation interaction
    # ImPlot3DFlags_NoZoom      : Lock zoom interaction
    # ImPlot3DFlags_NoInputs    : Disable all user inputs
    cffi::enum define ImPlot3DFlags_ {
        ImPlot3DFlags_None        0
        ImPlot3DFlags_NoTitle     1
        ImPlot3DFlags_NoLegend    2
        ImPlot3DFlags_NoMouseText 4
        ImPlot3DFlags_NoClip      8
        ImPlot3DFlags_NoMenus     16
        ImPlot3DFlags_Equal       32
        ImPlot3DFlags_NoRotate    64
        ImPlot3DFlags_NoPan       128
        ImPlot3DFlags_NoZoom      256
        ImPlot3DFlags_NoInputs    512
        ImPlot3DFlags_CanvasOnly  7
    }

    # ImPlot3DImageFlags_None     : Default
    cffi::enum define ImPlot3DImageFlags_ {
        ImPlot3DImageFlags_None     0
        ImPlot3DImageFlags_NoLegend 1
        ImPlot3DImageFlags_NoFit    2
    }

    # ImPlot3DItemFlags_None     : Default
    # ImPlot3DItemFlags_NoLegend : The item won't have a legend entry displayed
    # ImPlot3DItemFlags_NoFit    : The item won't be considered for plot fits
    cffi::enum define ImPlot3DItemFlags_ {
        ImPlot3DItemFlags_None     0
        ImPlot3DItemFlags_NoLegend 1
        ImPlot3DItemFlags_NoFit    2
    }

    # ImPlot3DLegendFlags_None            : Default
    # ImPlot3DLegendFlags_NoButtons       : Legend icons will not function as hide/show buttons
    # ImPlot3DLegendFlags_NoHighlightItem : Plot items will not be highlighted when their legend entry is hovered
    # ImPlot3DLegendFlags_Horizontal      : Legend entries will be displayed horizontally
    cffi::enum define ImPlot3DLegendFlags_ {
        ImPlot3DLegendFlags_None            0
        ImPlot3DLegendFlags_NoButtons       1
        ImPlot3DLegendFlags_NoHighlightItem 2
        ImPlot3DLegendFlags_Horizontal      4
    }

    # ImPlot3DLineFlags_None     : Default
    # ImPlot3DLineFlags_Segments : A line segment will be rendered from every two consecutive points
    # ImPlot3DLineFlags_Loop     : The last and first point will be connected to form a closed loop
    # ImPlot3DLineFlags_SkipNaN  : NaNs values will be skipped instead of rendered as missing data
    cffi::enum define ImPlot3DLineFlags_ {
        ImPlot3DLineFlags_None     0
        ImPlot3DLineFlags_NoLegend 1
        ImPlot3DLineFlags_NoFit    2
        ImPlot3DLineFlags_Segments 1024
        ImPlot3DLineFlags_Loop     2048
        ImPlot3DLineFlags_SkipNaN  4096
    }

    # ImPlot3DLocation_Center    : Center-center
    # ImPlot3DLocation_North     : Top-center
    # ImPlot3DLocation_South     : Bottom-center
    # ImPlot3DLocation_West      : Center-left
    # ImPlot3DLocation_East      : Center-right
    # ImPlot3DLocation_NorthWest : Top-left
    # ImPlot3DLocation_NorthEast : Top-right
    # ImPlot3DLocation_SouthWest : Bottom-left
    # ImPlot3DLocation_SouthEast : Bottom-right
    cffi::enum define ImPlot3DLocation_ {
        ImPlot3DLocation_Center    0
        ImPlot3DLocation_North     1
        ImPlot3DLocation_South     2
        ImPlot3DLocation_West      4
        ImPlot3DLocation_East      8
        ImPlot3DLocation_NorthWest 5
        ImPlot3DLocation_NorthEast 9
        ImPlot3DLocation_SouthWest 6
        ImPlot3DLocation_SouthEast 10
    }

    # ImPlot3DMarker_None     : No marker
    # ImPlot3DMarker_Auto     : Automatic marker selection
    # ImPlot3DMarker_Circle   : Circle marker (default)
    # ImPlot3DMarker_Square   : Square maker
    # ImPlot3DMarker_Diamond  : Diamond marker
    # ImPlot3DMarker_Up       : Upward-pointing triangle marker
    # ImPlot3DMarker_Down     : Downward-pointing triangle marker
    # ImPlot3DMarker_Left     : Leftward-pointing triangle marker
    # ImPlot3DMarker_Right    : Rightward-pointing triangle marker
    # ImPlot3DMarker_Cross    : Cross marker (not fillable)
    # ImPlot3DMarker_Plus     : Plus marker (not fillable)
    # ImPlot3DMarker_Asterisk : Asterisk marker (not fillable)
    cffi::enum define ImPlot3DMarker_ {
        ImPlot3DMarker_None     -2
        ImPlot3DMarker_Auto     -1
        ImPlot3DMarker_Circle   0
        ImPlot3DMarker_Square   1
        ImPlot3DMarker_Diamond  2
        ImPlot3DMarker_Up       3
        ImPlot3DMarker_Down     4
        ImPlot3DMarker_Left     5
        ImPlot3DMarker_Right    6
        ImPlot3DMarker_Cross    7
        ImPlot3DMarker_Plus     8
        ImPlot3DMarker_Asterisk 9
        ImPlot3DMarker_COUNT    10
    }

    # ImPlot3DMeshFlags_None      : Default
    # ImPlot3DMeshFlags_NoLines   : No lines will be rendered
    # ImPlot3DMeshFlags_NoFill    : No fill will be rendered
    # ImPlot3DMeshFlags_NoMarkers : No markers will be rendered
    cffi::enum define ImPlot3DMeshFlags_ {
        ImPlot3DMeshFlags_None      0
        ImPlot3DMeshFlags_NoLegend  1
        ImPlot3DMeshFlags_NoFit     2
        ImPlot3DMeshFlags_NoLines   1024
        ImPlot3DMeshFlags_NoFill    2048
        ImPlot3DMeshFlags_NoMarkers 4096
    }

    # ImPlot3DProp_LineColor        : Line color; IMPLOT3D_AUTO_COL will use next Colormap color
    # ImPlot3DProp_LineColors       : Array of line colors (ImU32*); if nullptr, use LineColor for all
    # ImPlot3DProp_LineWeight       : Line weight in pixels
    # ImPlot3DProp_FillColor        : Fill color (applies to shaded regions); IMPLOT3D_AUTO_COL will use next Colormap color
    # ImPlot3DProp_FillColors       : Array of fill colors (ImU32*); if nullptr, use FillColor for all
    # ImPlot3DProp_FillAlpha        : Alpha multiplier (applies to FillColor, FillColors, MarkerFillColor, and MarkerFillColors)
    # ImPlot3DProp_Marker           : Marker type
    # ImPlot3DProp_MarkerSize       : Size of markers (radius) *in pixels*
    # ImPlot3DProp_MarkerSizes      : Array of marker sizes (float*); if nullptr, use MarkerSize for all
    # ImPlot3DProp_MarkerLineColor  : Marker outline color; IMPLOT3D_AUTO_COL will use next LineColor
    # ImPlot3DProp_MarkerLineColors : Array of marker outline colors (ImU32*); if nullptr, use MarkerLineColor for all
    # ImPlot3DProp_MarkerFillColor  : Marker fill color; IMPLOT3D_AUTO_COL will use LineColor
    # ImPlot3DProp_MarkerFillColors : Array of marker fill colors (ImU32*); if nullptr, use MarkerFillColor for all
    # ImPlot3DProp_Offset           : Data index offset
    # ImPlot3DProp_Stride           : Data stride in bytes; IMPLOT3D_AUTO will result in sizeof(T) where T is the type passed to PlotX
    # ImPlot3DProp_Flags            : Optional item flags; can be composed from common ImPlot3DItemFlags and/or specialized ImPlot3DXFlags
    cffi::enum define ImPlot3DProp_ {
        ImPlot3DProp_LineColor        0
        ImPlot3DProp_LineColors       1
        ImPlot3DProp_LineWeight       2
        ImPlot3DProp_FillColor        3
        ImPlot3DProp_FillColors       4
        ImPlot3DProp_FillAlpha        5
        ImPlot3DProp_Marker           6
        ImPlot3DProp_MarkerSize       7
        ImPlot3DProp_MarkerSizes      8
        ImPlot3DProp_MarkerLineColor  9
        ImPlot3DProp_MarkerLineColors 10
        ImPlot3DProp_MarkerFillColor  11
        ImPlot3DProp_MarkerFillColors 12
        ImPlot3DProp_Offset           13
        ImPlot3DProp_Stride           14
        ImPlot3DProp_Flags            15
    }

    # ImPlot3DQuadFlags_None      : Default
    # ImPlot3DQuadFlags_NoLines   : No lines will be rendered
    # ImPlot3DQuadFlags_NoFill    : No fill will be rendered
    # ImPlot3DQuadFlags_NoMarkers : No markers will be rendered
    cffi::enum define ImPlot3DQuadFlags_ {
        ImPlot3DQuadFlags_None      0
        ImPlot3DQuadFlags_NoLegend  1
        ImPlot3DQuadFlags_NoFit     2
        ImPlot3DQuadFlags_NoLines   1024
        ImPlot3DQuadFlags_NoFill    2048
        ImPlot3DQuadFlags_NoMarkers 4096
    }

    # ImPlot3DScale_Linear : Default linear scale
    # ImPlot3DScale_Log10  : Base 10 log scale
    # ImPlot3DScale_SymLog : Symmetric base 10 log scale
    cffi::enum define ImPlot3DScale_ {
        ImPlot3DScale_Linear 0
        ImPlot3DScale_Log10  1
        ImPlot3DScale_SymLog 2
    }

    # ImPlot3DScatterFlags_None     : Default
    cffi::enum define ImPlot3DScatterFlags_ {
        ImPlot3DScatterFlags_None     0
        ImPlot3DScatterFlags_NoLegend 1
        ImPlot3DScatterFlags_NoFit    2
    }

    # ImPlot3DItemFlags_NoLegend      : The item won't have a legend entry displayed
    # ImPlot3DItemFlags_NoFit         : The item won't be considered for plot fits
    # ImPlot3DLineFlags_Segments      : A line segment will be rendered from every two consecutive points
    # ImPlot3DLineFlags_Loop          : The last and first point will be connected to form a closed loop
    # ImPlot3DLineFlags_SkipNaN       : NaNs values will be skipped instead of rendered as missing data
    # ImPlot3DTriangleFlags_NoLines   : No lines will be rendered
    # ImPlot3DTriangleFlags_NoFill    : No fill will be rendered
    # ImPlot3DTriangleFlags_NoMarkers : No markers will be rendered
    # ImPlot3DQuadFlags_NoLines       : No lines will be rendered
    # ImPlot3DQuadFlags_NoFill        : No fill will be rendered
    # ImPlot3DQuadFlags_NoMarkers     : No markers will be rendered
    # ImPlot3DSurfaceFlags_NoLines    : No lines will be rendered
    # ImPlot3DSurfaceFlags_NoFill     : No fill will be rendered
    # ImPlot3DSurfaceFlags_NoMarkers  : No markers will be rendered
    # ImPlot3DMeshFlags_NoLines       : No lines will be rendered
    # ImPlot3DMeshFlags_NoFill        : No fill will be rendered
    # ImPlot3DMeshFlags_NoMarkers     : No markers will be rendered
    cffi::enum define ImPlot3DSpecFlags_ {
        ImPlot3DSpecFlags_None          0
        ImPlot3DItemFlags_NoLegend      1
        ImPlot3DItemFlags_NoFit         2
        ImPlot3DScatterFlags_NoLegend   1
        ImPlot3DScatterFlags_NoFit      2
        ImPlot3DLineFlags_NoLegend      1
        ImPlot3DLineFlags_NoFit         2
        ImPlot3DLineFlags_Segments      1024
        ImPlot3DLineFlags_Loop          2048
        ImPlot3DLineFlags_SkipNaN       4096
        ImPlot3DTriangleFlags_NoLegend  1
        ImPlot3DTriangleFlags_NoFit     2
        ImPlot3DTriangleFlags_NoLines   1024
        ImPlot3DTriangleFlags_NoFill    2048
        ImPlot3DTriangleFlags_NoMarkers 4096
        ImPlot3DQuadFlags_NoLegend      1
        ImPlot3DQuadFlags_NoFit         2
        ImPlot3DQuadFlags_NoLines       1024
        ImPlot3DQuadFlags_NoFill        2048
        ImPlot3DQuadFlags_NoMarkers     4096
        ImPlot3DSurfaceFlags_NoLegend   1
        ImPlot3DSurfaceFlags_NoFit      2
        ImPlot3DSurfaceFlags_NoLines    1024
        ImPlot3DSurfaceFlags_NoFill     2048
        ImPlot3DSurfaceFlags_NoMarkers  4096
        ImPlot3DMeshFlags_NoLegend      1
        ImPlot3DMeshFlags_NoFit         2
        ImPlot3DMeshFlags_NoLines       1024
        ImPlot3DMeshFlags_NoFill        2048
        ImPlot3DMeshFlags_NoMarkers     4096
        ImPlot3DImageFlags_NoLegend     1
        ImPlot3DImageFlags_NoFit        2
    }

    # ImPlot3DStyleVar_LineWeight         : float, plot item line weight in pixels
    # ImPlot3DStyleVar_Marker             : int,   marker specification
    # ImPlot3DStyleVar_MarkerSize         : float, marker size in pixels (roughly the marker's "radius")
    # ImPlot3DStyleVar_FillAlpha          : float, alpha modifier applied to all plot item fills
    # ImPlot3DStyleVar_PlotDefaultSize    : ImVec2, default size used when ImVec2(0,0) is passed to BeginPlot
    # ImPlot3DStyleVar_PlotMinSize        : ImVec2, minimum size plot frame can be when shrunk
    # ImPlot3DStyleVar_PlotPadding        : ImVec2, padding between widget frame and plot area, labels, or outside legends (i.e. main padding)
    # ImPlot3DStyleVar_LabelPadding       : ImVec2, padding between axes labels, tick labels, and plot edge
    # ImPlot3DStyleVar_ViewScaleFactor    : float, scale factor for 3D view, you can use it to make the whole plot larger or smaller
    # ImPlot3DStyleVar_LegendPadding      : ImVec2, legend padding from plot edges
    # ImPlot3DStyleVar_LegendInnerPadding : ImVec2, legend inner padding from legend edges
    # ImPlot3DStyleVar_LegendSpacing      : ImVec2, spacing between legend entries
    cffi::enum define ImPlot3DStyleVar_ {
        ImPlot3DStyleVar_LineWeight         0
        ImPlot3DStyleVar_Marker             1
        ImPlot3DStyleVar_MarkerSize         2
        ImPlot3DStyleVar_FillAlpha          3
        ImPlot3DStyleVar_PlotDefaultSize    4
        ImPlot3DStyleVar_PlotMinSize        5
        ImPlot3DStyleVar_PlotPadding        6
        ImPlot3DStyleVar_LabelPadding       7
        ImPlot3DStyleVar_ViewScaleFactor    8
        ImPlot3DStyleVar_LegendPadding      9
        ImPlot3DStyleVar_LegendInnerPadding 10
        ImPlot3DStyleVar_LegendSpacing      11
        ImPlot3DStyleVar_COUNT              12
    }

    # ImPlot3DSurfaceFlags_None      : Default
    # ImPlot3DSurfaceFlags_NoLines   : No lines will be rendered
    # ImPlot3DSurfaceFlags_NoFill    : No fill will be rendered
    # ImPlot3DSurfaceFlags_NoMarkers : No markers will be rendered
    cffi::enum define ImPlot3DSurfaceFlags_ {
        ImPlot3DSurfaceFlags_None      0
        ImPlot3DSurfaceFlags_NoLegend  1
        ImPlot3DSurfaceFlags_NoFit     2
        ImPlot3DSurfaceFlags_NoLines   1024
        ImPlot3DSurfaceFlags_NoFill    2048
        ImPlot3DSurfaceFlags_NoMarkers 4096
    }

    # ImPlot3DTriangleFlags_None      : Default
    # ImPlot3DTriangleFlags_NoLines   : No lines will be rendered
    # ImPlot3DTriangleFlags_NoFill    : No fill will be rendered
    # ImPlot3DTriangleFlags_NoMarkers : No markers will be rendered
    cffi::enum define ImPlot3DTriangleFlags_ {
        ImPlot3DTriangleFlags_None      0
        ImPlot3DTriangleFlags_NoLegend  1
        ImPlot3DTriangleFlags_NoFit     2
        ImPlot3DTriangleFlags_NoLines   1024
        ImPlot3DTriangleFlags_NoFill    2048
        ImPlot3DTriangleFlags_NoMarkers 4096
    }

    cffi::alias define ImAxis3D              {int {enum ImAxis3D_}}
    cffi::alias define ImPlane3D             {int {enum ImPlane3D_}}
    cffi::alias define ImPlot3DAxisFlags     {int {enum ImPlot3DAxisFlags_}}
    cffi::alias define ImPlot3DCol           {int {enum ImPlot3DCol_}}
    cffi::alias define ImPlot3DColormap      {int {enum ImPlot3DColormap_}}
    cffi::alias define ImPlot3DCond          {int {enum ImPlot3DCond_}}
    cffi::alias define ImPlot3DDummyFlags    {int {enum ImPlot3DDummyFlags_}}
    cffi::alias define ImPlot3DFlags         {int {enum ImPlot3DFlags_}}
    cffi::alias define ImPlot3DImageFlags    {int {enum ImPlot3DImageFlags_}}
    cffi::alias define ImPlot3DItemFlags     {int {enum ImPlot3DItemFlags_}}
    cffi::alias define ImPlot3DLegendFlags   {int {enum ImPlot3DLegendFlags_}}
    cffi::alias define ImPlot3DLineFlags     {int {enum ImPlot3DLineFlags_}}
    cffi::alias define ImPlot3DLocation      {int {enum ImPlot3DLocation_}}
    cffi::alias define ImPlot3DMarker        {int {enum ImPlot3DMarker_}}
    cffi::alias define ImPlot3DMeshFlags     {int {enum ImPlot3DMeshFlags_}}
    cffi::alias define ImPlot3DProp          {int {enum ImPlot3DProp_}}
    cffi::alias define ImPlot3DQuadFlags     {int {enum ImPlot3DQuadFlags_}}
    cffi::alias define ImPlot3DScale         {int {enum ImPlot3DScale_}}
    cffi::alias define ImPlot3DScatterFlags  {int {enum ImPlot3DScatterFlags_}}
    cffi::alias define ImPlot3DSpecFlags     {int {enum ImPlot3DSpecFlags_}}
    cffi::alias define ImPlot3DStyleVar      {int {enum ImPlot3DStyleVar_}}
    cffi::alias define ImPlot3DSurfaceFlags  {int {enum ImPlot3DSurfaceFlags_}}
    cffi::alias define ImPlot3DTriangleFlags {int {enum ImPlot3DTriangleFlags_}}
}
