# Copyright (c) 2022-2026 Nicolas ROBERT.
# Distributed under MIT license. Please see LICENSE for details.
#
# This file is generated by generator/generate.tcl, do not edit by hand.

namespace eval ::implot3d {
    cffi::Struct create ImPlot3DPoint {
        x double
        y double
        z double
    }

    cffi::Struct create ImPlot3DBox {
        Min struct.ImPlot3DPoint
        Max struct.ImPlot3DPoint
    }

    cffi::Struct create ImPlot3DPlane {
        Point  struct.ImPlot3DPoint
        Normal struct.ImPlot3DPoint
    }

    cffi::Struct create ImPlot3DQuat {
        x double
        y double
        z double
        w double
    }

    cffi::Struct create ImPlot3DRange {
        Min double
        Max double
    }

    cffi::Struct create ImPlot3DRay {
        Origin    struct.ImPlot3DPoint
        Direction struct.ImPlot3DPoint
    }

    cffi::Struct create ImPlot3DSpec {
        LineColor        {struct.::imgui::ImVec4 {default {x 0 y 0 z 0 w -1}}}
        LineColors       {pointer nullok {default NULL}}
        LineWeight       {float {default 1.0}}
        FillColor        {struct.::imgui::ImVec4 {default {x 0 y 0 z 0 w -1}}}
        FillColors       {pointer nullok {default NULL}}
        FillAlpha        {float {default -1}}
        Marker           {ImPlot3DMarker {default ImPlot3DMarker_Auto}}
        MarkerSize       {float {default -1}}
        MarkerSizes      {pointer nullok {default NULL}}
        MarkerLineColor  {struct.::imgui::ImVec4 {default {x 0 y 0 z 0 w -1}}}
        MarkerLineColors {pointer nullok {default NULL}}
        MarkerFillColor  {struct.::imgui::ImVec4 {default {x 0 y 0 z 0 w -1}}}
        MarkerFillColors {pointer nullok {default NULL}}
        Offset           {int {default 0}}
        Stride           {int {default -1}}
        Flags            {ImPlot3DSpecFlags bitmask {default 0}}
    }

    cffi::Struct create ImPlot3DStyle {
        LineWeight         float
        Marker             int
        MarkerSize         float
        FillAlpha          float
        PlotDefaultSize    struct.::imgui::ImVec2
        PlotMinSize        struct.::imgui::ImVec2
        PlotPadding        struct.::imgui::ImVec2
        LabelPadding       struct.::imgui::ImVec2
        ViewScaleFactor    float
        LegendPadding      struct.::imgui::ImVec2
        LegendInnerPadding struct.::imgui::ImVec2
        LegendSpacing      struct.::imgui::ImVec2
        Colors             struct.::imgui::ImVec4[14]
        Colormap           ImPlot3DColormap
    }

}
