# Copyright (c) 2022-2026 Nicolas ROBERT.
# Distributed under MIT license. Please see LICENSE for details.

# Generates the cffi declarations of implottk from the cimgui / cimplot /
# cimplot3d generator outputs (generator/json_cimgui/, json_cimplot/ and
# json_cimplot3d/ folders) :
#
#   src/imgui/alias.tcl    : typedefs (ImU32, ImGuiID, ImTextureID...)
#   src/imgui/enums.tcl    : enums + enum aliases
#   src/imgui/structs.tcl  : structs and unions
#   src/implot/enums.tcl   : enums + enum aliases
#   src/implot/structs.tcl : structs and unions
#   src/implot3d/enums.tcl   : enums + enum aliases
#   src/implot3d/structs.tcl : structs
#
# 'implot/alias.tcl' (callbacks prototypes) and the '*/funcs.tcl' files
# are maintained by hand.
#
# Usage : tclsh generator/generate.tcl ?-check?
#
#   -check : generates nothing, compares the functions declared by hand
#            ('*/funcs.tcl') with the cimgui / cimplot / cimplot3d definitions
#            ('definitions.json') : missing functions, number and types of
#            the parameters, return type and default values.
#            Exit code 1 if differences are found.
#
# Requires Tcl 9 + tcllib (json).

package require Tcl 9.0
package require json

namespace eval ::gen {
    variable root [file dirname [file dirname [file normalize [info script]]]]
    variable header {# Copyright (c) 2022-2026 Nicolas ROBERT.
# Distributed under MIT license. Please see LICENSE for details.
#
# This file is generated by generator/generate.tcl, do not edit by hand.}

    # C base types -> cffi types.
    variable basetypes {
        bool                 ImBool
        char                 schar
        {signed char}        schar
        {unsigned char}      uchar
        short                short
        {signed short}       short
        {unsigned short}     ushort
        int                  int
        {signed int}         int
        {unsigned int}       uint
        long                 long
        {unsigned long}      ulong
        {long long}          longlong
        {signed long long}   longlong
        {unsigned long long} ulonglong
        float                float
        double               double
        size_t               size_t
        time_t               time_t
    }

    # Old structs needed by the package even if they are 'internal'.
    variable extrastructs {
        imgui  {ImRect}
        implot {
            ImPlotContext ImPlotPlot ImPlotSubplot ImPlotItem ImPlotItemGroup
            ImPlotLegend ImPlotAxis ImPlotTick ImPlotTicker ImPlotTagCollection
            ImPlotTag ImPlotAnnotationCollection ImPlotAnnotation ImPlotNextPlotData
            ImPlotNextItemData ImPlotColormapData ImPlotAlignmentData
            ImPlotDateTimeSpec ImPlotTime ImPlotPointError ImPlotInputMap
        }
        implot3d {}
    }

    # Default values of struct fields (from implot.h), so that a struct can
    # be passed as a partial dict, e.g. {LineColor {x 1 y 0 z 0 w 1}}.
    variable fielddefaults {
        ImPlotSpec {
            LineColor        {x 0 y 0 z 0 w -1}
            LineColors       NULL
            LineWeight       1.0
            FillColor        {x 0 y 0 z 0 w -1}
            FillColors       NULL
            FillAlpha        1.0
            Marker           ImPlotMarker_None
            MarkerSize       4
            MarkerSizes      NULL
            MarkerLineColor  {x 0 y 0 z 0 w -1}
            MarkerLineColors NULL
            MarkerFillColor  {x 0 y 0 z 0 w -1}
            MarkerFillColors NULL
            Size             4
            Offset           0
            Stride           -1
            Flags            0
        }
        ImPlot3DSpec {
            LineColor        {x 0 y 0 z 0 w -1}
            LineColors       NULL
            LineWeight       1.0
            FillColor        {x 0 y 0 z 0 w -1}
            FillColors       NULL
            FillAlpha        -1
            Marker           ImPlot3DMarker_Auto
            MarkerSize       -1
            MarkerSizes      NULL
            MarkerLineColor  {x 0 y 0 z 0 w -1}
            MarkerLineColors NULL
            MarkerFillColor  {x 0 y 0 z 0 w -1}
            MarkerFillColors NULL
            Offset           0
            Stride           -1
            Flags            0
        }
    }

    # ImPlotSpec.Flags accepts the common item flags and the flags of
    # every plot type : an enum gathering all of them is generated.
    # (same for ImPlot3DSpec.Flags).
    variable specflags {
        ImPlotSpecFlags_ {
            ImPlotItemFlags_ ImPlotLineFlags_ ImPlotScatterFlags_ ImPlotStairsFlags_
            ImPlotShadedFlags_ ImPlotBarsFlags_ ImPlotBarGroupsFlags_
            ImPlotErrorBarsFlags_ ImPlotStemsFlags_ ImPlotInfLinesFlags_
            ImPlotPieChartFlags_ ImPlotHeatmapFlags_ ImPlotHistogramFlags_
            ImPlotDigitalFlags_ ImPlotImageFlags_ ImPlotTextFlags_ ImPlotDummyFlags_
            ImPlotBubblesFlags_ ImPlotPolygonFlags_
        }
        ImPlot3DSpecFlags_ {
            ImPlot3DItemFlags_ ImPlot3DScatterFlags_ ImPlot3DLineFlags_
            ImPlot3DTriangleFlags_ ImPlot3DQuadFlags_ ImPlot3DSurfaceFlags_
            ImPlot3DMeshFlags_ ImPlot3DImageFlags_ ImPlot3DDummyFlags_
        }
    }

    # Default values of parameters different from C on purpose (-check).
    variable checkignore {
        ImPlot_BeginPlot {size {x -1 y -1 : the plot fills the window}}
        ImPlot3D_BeginPlot {size {x -1 y -1 : the plot fills the window}}
    }

    # Internal structs never generated (opaque for implottk, too large and
    # use bitfields that cffi can't represent).
    variable excluded {ImGuiContext}

    # Templates : the memory layout doesn't depend on 'T' (pointers only).
    variable templates {
        ImVector      {Size int Capacity int Data pointer}
        ImSpan        {Data pointer DataEnd pointer}
        ImChunkStream {Buf struct.::imgui::ImVector}
        ImPool        {
            Buf        struct.::imgui::ImVector
            Map        struct.::imgui::ImGuiStorage
            FreeIdx    ImPoolIdx
            AliveCount ImPoolIdx
        }
    }
}

proc ::gen::readJson {file} {
    set fp [open $file r]
    fconfigure $fp -encoding utf-8
    set data [json::json2dict [read $fp]]
    close $fp
    return $data
}

proc ::gen::readFile {file} {
    set fp [open $file r]
    fconfigure $fp -encoding utf-8
    set data [read $fp]
    close $fp
    return $data
}

proc ::gen::writeFile {file content} {
    set fp [open $file w]
    fconfigure $fp -encoding utf-8 -translation lf
    puts -nonewline $fp $content
    close $fp
    puts "  -> [file tail [file dirname $file]]/[file tail $file]"
}

proc ::gen::enumComments {headers} {
    # Extract the comment of each enum value, the line must start with
    # the value name (avoids picking up a comment of another value).
    #
    # Returns dict name -> comment
    set comments {}
    foreach h $headers {
        foreach line [split [readFile $h] \n] {
            if {[regexp {^\s*(Im\w+)\s*(?:=[^,]*)?,?\s*//\s*(.*)$} $line -> name comment]} {
                if {![dict exists $comments $name]} {
                    dict set comments $name [string trim $comment]
                }
            }
        }
    }
    return $comments
}

proc ::gen::aliasName {enumname} {
    return [string trimright $enumname _]
}

proc ::gen::genEnums {ns enums comments} {
    variable header

    set out "$header\n\nnamespace eval ::$ns \{\n"
    set aliases {}

    foreach enumname [lsort -dictionary [dict keys $enums]] {
        set values [dict get $enums $enumname]
        set w 0
        foreach v $values {
            set w [expr {max($w, [string length [dict get $v name]])}]
        }
        set coms {}
        foreach v $values {
            set n [dict get $v name]
            if {[dict exists $comments $n] && [dict get $comments $n] ne ""} {
                lappend coms [format "    # %-${w}s : %s" $n [dict get $comments $n]]
            }
        }
        if {[llength $coms]} {
            append out [join $coms \n] \n
        }
        append out "    cffi::enum define $enumname \{\n"
        foreach v $values {
            append out [format "        %-${w}s %s" [dict get $v name] [dict get $v calc_value]] \n
        }
        append out "    \}\n\n"
        lappend aliases [aliasName $enumname] $enumname
    }

    set w 0
    foreach {a -} $aliases {set w [expr {max($w, [string length $a])}]}
    foreach {a e} $aliases {
        append out [format "    cffi::alias define %-${w}s {int {enum %s}}" $a $e] \n
    }
    append out "\}\n"

    return $out
}

proc ::gen::resolveTypedef {name typedefs} {
    # Returns the cffi type of a typedef or "" if it cannot be represented.
    variable basetypes
    set t [string trim [dict get $typedefs $name] " ;"]

    if {[string match "struct *" $t]} {return ""}
    if {[string first "(*)" $t] > -1} {return pointer}
    if {[string index $t end] eq "*"} {return pointer}
    if {[dict exists $basetypes $t]} {return [dict get $basetypes $t]}
    if {[dict exists $typedefs $t]} {return $t}
    return ""
}

proc ::gen::genAlias {typedefs enumaliases} {
    variable header
    # Typedefs : define dependencies first.
    set done {}
    set lines {}
    set pending [lsort -dictionary [dict keys $typedefs]]
    while {[llength $pending]} {
        set next {}
        foreach name $pending {
            if {$name in $enumaliases} continue
            set t [resolveTypedef $name $typedefs]
            if {$t eq ""} continue
            if {[dict exists $typedefs $t] && $t ni $done} {
                lappend next $name
                continue
            }
            lappend lines [list $name $t]
            lappend done $name
        }
        if {[llength $next] == [llength $pending]} break
        set pending $next
    }
    set w 0
    foreach l $lines {set w [expr {max($w, [string length [lindex $l 0]])}]}

    set out "$header\n\n"
    foreach l $lines {
        append out [format "cffi::alias define %-${w}s %s" {*}$l] \n
    }
    append out "\n# define bool as type for struct\n"
    append out [format "cffi::alias define %-${w}s %s" ImBool uchar] \n
    append out "# define bool as type for function\n"
    append out [format "cffi::alias define %-${w}s %s" CIMGUI_BOOL uchar] \n
    return $out
}

proc ::gen::fieldType {ctype ns structs typedefs owner field} {
    # Converts a C member type into a cffi type.
    #
    # ctype   - C type
    # ns      - namespace of the struct being generated
    # structs - dict structname -> namespace (generated structs)
    #
    # Returns cffi type
    variable basetypes
    variable templates

    set t [string trim [regsub -all {\mconst\M} $ctype ""]]
    regsub -all {\s+} $t " " t

    if {[string first "(*)" $t] > -1}    {return pointer}
    if {[string index $t end] eq "*"} {
        set base [string trim [string trimright $t "*"]]
        if {[string index $t end-1] eq "*"} {return pointer}
        if {[dict exists $structs $base]} {
            return pointer.[qualify $base $ns $structs]
        }
        return pointer
    }
    if {[regexp {^(ImVector|ImSpan|ImChunkStream|ImPool)_\w+$} $t -> tpl]} {
        return struct.::imgui::$tpl
    }
    if {[dict exists $basetypes $t]} {return [dict get $basetypes $t]}
    if {$t eq "tm"} {return struct.::imgui::tm}
    if {[dict exists $structs $t]} {
        return struct.[qualify $t $ns $structs]
    }
    variable enumns
    if {[dict exists $enumns $t]} {
        if {[dict get $enumns $t] eq $ns} {return $t}
        return ::[dict get $enumns $t]::$t
    }
    if {[dict exists $typedefs $t]} {
        # Function pointer
        if {[string first "(*)" [dict get $typedefs $t]] > -1} {return pointer}
        return $t
    }

    error "$owner.$field : unknown type '$ctype'"
}

proc ::gen::qualify {name ns structs} {
    set sns [dict get $structs $name]
    if {$sns eq $ns} {return $name}
    return ::${sns}::$name
}

proc ::gen::members {sname mlist ns structs typedefs unionsVar} {
    # Returns list {name cffitype ...} of a struct (bitfields packed, unions named)
    upvar 1 $unionsVar unions
    set fields {}
    set bits 0
    set bitname {}
    set bittype {}
    set nunion 0

    foreach m $mlist {
        set name [dict get $m name]
        set ctype [dict get $m type]

        # Bitfields : packed into one field of the base type.
        if {[dict exists $m bitfield]} {
            set n [dict get $m bitfield]
            set ft [fieldType $ctype $ns $structs $typedefs $sname $name]
            if {$bittype eq $ft && $bits + $n <= 32} {
                lappend bitname $name
                incr bits $n
                continue
            }
            if {$bittype ne ""} {lappend fields [join $bitname _] $bittype}
            set bittype $ft ; set bitname [list $name] ; set bits $n
            continue
        } elseif {$bittype ne ""} {
            lappend fields [join $bitname _] $bittype
            set bittype {} ; set bitname {} ; set bits 0
        }

        # Anonymous unions
        if {[regexp {^union\s*\{(.*)\}$} $ctype -> body]} {
            set uname ${sname}_Union[expr {$nunion ? $nunion : ""}]
            incr nunion
            set ufields {}
            foreach decl [split $body ";"] {
                set decl [string trim $decl]
                if {$decl eq ""} continue
                regexp {^(.*?)\s*(\w+)(\[\w+\])?$} $decl -> ut un arr
                set ft [fieldType $ut $ns $structs $typedefs $sname $un]
                if {$arr ne ""} {append ft $arr}
                lappend ufields $un $ft
            }
            lappend unions $uname $ufields
            lappend fields u union.$uname
            continue
        }

        set ft [fieldType $ctype $ns $structs $typedefs $sname $name]
        if {[regexp {^(\w+)\[(.*)\]$} $name -> base -]} {
            set name $base
            append ft "\[[dict get $m size]\]"
        }
        lappend fields $name $ft
    }
    if {$bittype ne ""} {lappend fields [join $bitname _] $bittype}

    return $fields
}

proc ::gen::deps {fields ns} {
    # By-value struct dependencies of a struct.
    set d {}
    foreach {- t} $fields {
        if {[regexp {^(?:struct|union)\.(?:::(\w+)::)?(\w+)} $t -> dns dname]} {
            lappend d $dname
        }
    }
    return $d
}

proc ::gen::selectStructs {jsons extra} {
    # Public structs (imgui.h / implot.h / implot3d.h) + extra structs +
    # by-value deps.
    #
    # Returns dict structname -> namespace
    set structs {}
    set want {}
    foreach {ns json} $jsons {
        dict for {name loc} [dict get $json locations] {
            if {![dict exists $json structs $name]} continue
            if {[regexp {^(imgui|implot|implot3d):} $loc]} {
                lappend want $name
            }
        }
        lappend want {*}[dict get $extra $ns]
    }

    set all {}
    foreach {ns json} $jsons {
        dict for {name -} [dict get $json structs] {
            if {![dict exists $all $name]} {dict set all $name [list $ns $json]}
        }
    }

    while {[llength $want]} {
        set name [lindex $want 0]
        set want [lrange $want 1 end]
        variable excluded
        if {[dict exists $structs $name] || ![dict exists $all $name]} continue
        if {$name in $excluded} continue
        lassign [dict get $all $name] ns json
        dict set structs $name $ns
        foreach m [dict get $json structs $name] {
            set t [string trim [regsub -all {\mconst\M} [dict get $m type] ""]]
            if {[string index $t end] eq "*"} continue
            foreach w [regexp -all -inline {\mIm\w+} $t] {
                if {[regexp {^(ImVector|ImSpan|ImChunkStream|ImPool)_} $w]} {
                    lappend want ImGuiStorage
                    continue
                }
                lappend want $w
            }
        }
    }
    return $structs
}

proc ::gen::genStructs {ns structs jsons typedefs} {
    variable header
    variable templates

    set defs {}
    set unions {}
    dict for {name sns} $structs {
        if {$sns ne $ns} continue
        set json [dict get $jsons $ns]
        dict set defs $name [members $name [dict get $json structs $name] $ns $structs $typedefs unions]
    }
    if {$ns eq "imgui"} {
        dict for {t f} $templates {dict set defs $t $f}
    }

    # Topological order (by-value deps).
    set order {}
    set state {}
    proc visit {n} {
        upvar 1 defs defs order order state state unions unions
        if {[dict exists $state $n]} return
        dict set state $n 1
        if {[dict exists $defs $n]} {
            set f [dict get $defs $n]
        } elseif {[dict exists $unions $n]} {
            set f [dict get $unions $n]
        } else {
            return
        }
        foreach d [::gen::deps $f ""] {visit $d}
        lappend order $n
    }
    foreach n [lsort -dictionary [dict keys $defs]] {visit $n}

    set out "$header\n\nnamespace eval ::$ns \{\n"
    if {$ns eq "imgui"} {
        append out {
    # 'struct tm' (C library) is used by ImPlotContext.
    if {$::tcl_platform(platform) eq "windows"} {
        cffi::Struct create tm {
            tm_sec int tm_min int tm_hour int tm_mday int tm_mon int
            tm_year int tm_wday int tm_yday int tm_isdst int
        }
    } else {
        cffi::Struct create tm {
            tm_sec int tm_min int tm_hour int tm_mday int tm_mon int
            tm_year int tm_wday int tm_yday int tm_isdst int
            tm_gmtoff long tm_zone pointer
        }
    }
}
        append out \n
    }
    foreach n $order {
        if {[dict exists $unions $n]} {
            set kind Union ; set f [dict get $unions $n]
        } else {
            set kind Struct ; set f [dict get $defs $n]
        }
        set w 0
        foreach {fn -} $f {set w [expr {max($w, [string length $fn])}]}
        variable fielddefaults
        append out "    cffi::$kind create $n \{\n"
        foreach {fn ft} $f {
            if {[dict exists $fielddefaults $n $fn]} {
                set dv [dict get $fielddefaults $n $fn]
                if {$fn eq "Flags" && $n in {ImPlotSpec ImPlot3DSpec}} {
                    set ft [list ${n}Flags bitmask [list default $dv]]
                } elseif {$dv eq "NULL"} {
                    set ft [list $ft nullok [list default $dv]]
                } else {
                    set ft [list $ft [list default $dv]]
                }
                set ft [list $ft]
            }
            # Pointers in structs are often NULL.
            if {[string match pointer* $ft]} {
                set ft [list [list $ft nullok]]
            }
            append out [format "        %-${w}s %s" $fn $ft] \n
        }
        append out "    \}\n\n"
    }
    append out "\}\n"
    return $out
}

proc ::gen::specFlags {enums name} {
    # Enum gathering the flags of every plot type (see 'specflags').
    #
    # Returns the enums with the new enum.
    variable specflags
    set all {}
    foreach e [dict get $specflags $name] {
        if {![dict exists $enums $e]} continue
        foreach v [dict get $enums $e] {
            if {[dict get $v calc_value] == 0} continue
            lappend all $v
        }
    }
    set none [list calc_value 0 name ${name}None value 0]
    dict set enums $name [linsert $all 0 $none]
    return $enums
}

proc ::gen::main {} {
    variable root
    variable extrastructs

    set ci [file join $root generator json_cimgui]
    set cp [file join $root generator json_cimplot]
    set c3 [file join $root generator json_cimplot3d]

    puts "Reading json files..."
    set imgui      [readJson [file join $ci structs_and_enums.json]]
    set implot     [readJson [file join $cp structs_and_enums.json]]
    set implot3d   [readJson [file join $c3 structs_and_enums.json]]
    set typedefs   [readJson [file join $ci typedefs_dict.json]]
    set typedefs   [dict merge $typedefs [readJson [file join $cp typedefs_dict.json]]]
    set typedefs   [dict merge $typedefs [readJson [file join $c3 typedefs_dict.json]]]

    # Enums defined in the implot json are only the ImPlot ones.
    set comments [enumComments [list \
        [file join $ci imgui.h] [file join $ci imgui_internal.h] \
        [file join $cp implot.h] [file join $cp implot_internal.h] \
        [file join $c3 implot3d.h] [file join $c3 implot3d_internal.h]]]

    variable enumns {}
    set enumaliases {}
    foreach {ns json} [list imgui $imgui implot $implot implot3d $implot3d] {
        foreach e [dict keys [dict get $json enums]] {
            lappend enumaliases [aliasName $e]
            dict set enumns [aliasName $e] $ns
        }
    }

    puts "Generating..."
    # Only the imgui typedefs go in imgui/alias.tcl (global namespace).
    set imtypedefs [readJson [file join $ci typedefs_dict.json]]
    writeFile [file join $root src imgui alias.tcl] [genAlias $imtypedefs $enumaliases]
    writeFile [file join $root src imgui enums.tcl] \
        [genEnums imgui [dict get $imgui enums] $comments]
    writeFile [file join $root src implot enums.tcl] \
        [genEnums implot [specFlags [dict get $implot enums] ImPlotSpecFlags_] $comments]
    writeFile [file join $root src implot3d enums.tcl] \
        [genEnums implot3d [specFlags [dict get $implot3d enums] ImPlot3DSpecFlags_] $comments]

    set jsons [list imgui $imgui implot $implot implot3d $implot3d]
    set structs [selectStructs $jsons $extrastructs]
    foreach ns {imgui implot implot3d} {
        writeFile [file join $root src $ns structs.tcl] [genStructs $ns $structs $jsons $typedefs]
    }
    puts "Done : [dict size $structs] structs."
}

# Check of the functions declared by hand (option -check).

proc ::gen::loadDeclarations {files} {
    # Loads the cffi declarations of the 'funcs.tcl' files, in a child
    # interpreter (no cffi, no library) : 'CIMGUI function' only records the
    # declaration.
    #
    # files - list of 'funcs.tcl' files.
    #
    # Returns list {cname ret params file} (cname : name of the C function).
    set i [interp create]
    $i eval {
        namespace eval ::cffi {proc prototype args {}}
        set ::records {}
        proc CIMGUI {cmd name ret params} {
            lappend ::records [list [lindex $name 0] $ret $params $::current]
            # The command of the function stops the caller (the function is
            # not called, a wrapper can declare several functions).
            uplevel 1 [list proc [lindex $name end] args {error "not called"}]
            return
        }
    }
    foreach file $files {
        set current [file join {*}[lrange [file split $file] end-1 end]]
        $i eval [list set ::current $current]
        $i eval [list source $file]
        # Lazy declarations : the list returned by 'init'.
        set ns [lindex [regexp -inline {proc\s+::(\w+)::init\s} [readFile $file]] 1]
        foreach {name func} [$i eval [list ::${ns}::init]] {
            $i eval [list lappend ::records [list $name {*}$func $current]]
        }
        # Tcl wrappers : called with dummy arguments, they declare their
        # function and stop.
        foreach p [$i eval [list info procs ::${ns}::*]] {
            if {[string first "CIMGUI function" [$i eval [list info body $p]]] < 0} continue
            set args {}
            foreach a [$i eval [list info args $p]] {
                if {[$i eval [list info default $p $a d]]} break
                lappend args 0
            }
            catch {$i eval [list $p {*}$args]}
        }
    }
    set records [$i eval {set ::records}]
    interp delete $i
    # Same function declared several times (variants) : once.
    set out {}
    set seen {}
    foreach r $records {
        set key [lrange $r 0 2]
        if {[dict exists $seen $key]} continue
        dict set seen $key 1
        lappend out $r
    }
    return $out
}

proc ::gen::normType {ctype} {
    # C type without 'const', '_c' suffix (cimgui structs by value) and
    # extra spaces.
    set t [regsub -all {\mconst\M} $ctype ""]
    set t [string trim [regsub -all {\s+} $t " "]]
    regsub {^(Im\w+)_c$} $t {\1} t
    regsub -all { \*} $t * t
    return $t
}

proc ::gen::compatible {ctype ttype structs callbacks} {
    # Checks a cffi type against a C type.
    #
    # ctype     - C type
    # ttype     - cffi type declaration {type annotation ...}
    # structs   - list of the structs names
    # callbacks - list of the function pointers typedefs
    #
    # Returns 1 if compatible.
    set c [normType $ctype]
    set t [lindex $ttype 0]
    set ann [lrange $ttype 1 end]
    # namespace of the cffi type : not significant here.
    regsub {(^|\.)(::)?\w+::} $t {\1} t

    if {[regexp {\[\w*\]$} $c]} {set c "[regsub {\[\w*\]$} $c {}]*"}

    if {$c in {char* char**}} {
        return [regexp {^(string|chars|pointer)} $t]
    }
    if {[string index $c end] in {* &} || $c in $callbacks} {
        if {"inout" in $ann || "out" in $ann} {return 1}
        if {[regexp {^(pointer|string|chars)} $t] || [regexp {\[\w+\]$} $t]} {
            return 1
        }
        return 0
    }
    if {$c eq "bool"} {
        return [expr {$t in {ImBool CIMGUI_BOOL uchar}}]
    }
    if {$c in {float double int size_t}} {
        if {$t eq $c} {return 1}
        # int parameter typed with an enum (ImPlotBin...).
        return [expr {$c eq "int" && [string match Im* $t]}]
    }
    if {$c in {{unsigned int} ImU32}} {
        return [expr {$t in {uint ImU32}}]
    }
    if {$c in $structs} {
        return [expr {$t eq "struct.$c"}]
    }
    if {$c eq "void"} {
        return [expr {$t eq "void"}]
    }
    # Enums, typedefs : same name, or the base type.
    return [expr {$t eq $c || $t in {int uint}}]
}

proc ::gen::cDefault {value enums} {
    # Converts a C default value into a Tcl value.
    #
    # Returns the value or "?" if it can't be converted.
    set v [string trim $value]
    set consts {
        NULL "" nullptr "" true 1 false 0 IMPLOT_AUTO -1
        FLT_MAX 3.4028234663852886e+38 FLT_MIN 1.1754943508222875e-38
        IMPLOT_AUTO_COL {0 0 0 -1}
        IMPLOT3D_AUTO -1 IMPLOT3D_AUTO_COL {0 0 0 -1}
    }
    if {[regexp {^"(.*)"$} $v -> s]} {return $s}
    regsub -all {(\d\.?\d*)f\M} $v {\1} v
    regsub -all {(\d)\.f\M} $v {\1} v
    if {[dict exists $consts $v]} {return [dict get $consts $v]}
    if {[dict exists $enums $v]} {return [dict get $enums $v]}
    # (default constructor, e.g. ImPlotRange() : not checked)
    if {[regexp {^Im\w+\((.+)\)$} $v -> fields]} {
        set out {}
        foreach f [split $fields ,] {
            set f [cDefault $f $enums]
            if {$f eq "?"} {return ?}
            lappend out $f
        }
        return $out
    }
    if {[string is double -strict $v]} {return $v}
    return ?
}

proc ::gen::sameDefault {cvalue tvalue enums} {
    # Compares a C default value with the cffi default.
    set c [cDefault $cvalue $enums]
    if {$c eq "?"} {return 1}
    # Struct : dict {x .. y ..} (cffi) or list of values.
    if {[llength $tvalue] > 1 && [llength $tvalue] % 2 == 0 && [llength $c] == [llength $tvalue] / 2} {
        set tvalue [dict values $tvalue]
    }
    if {[llength $c] == 0 && $tvalue in {"" NULL}} {return 1}
    if {[llength $c] != [llength $tvalue]} {return 0}
    foreach a $c b $tvalue {
        if {[dict exists $enums $b]} {set b [dict get $enums $b]}
        if {[string is double -strict $a] && [string is double -strict $b]} {
            if {abs($a - $b) > 1e-6 * max(1.0, abs($a))} {return 0}
        } elseif {$a ne $b} {
            return 0
        }
    }
    return 1
}

proc ::gen::check {} {
    # Compares the hand-written declarations with definitions.json.
    #
    # Returns the number of differences.
    variable root
    variable checkignore

    set defs {}
    set structs {}
    set enums {}
    # (ImPlotPoint_getter : cimplot '_LJ' functions, not in typedefs_dict.json)
    set callbacks {ImPlotPoint_getter}
    foreach dir {json_cimgui json_cimplot json_cimplot3d} {
        set d [file join $root generator $dir]
        foreach f {definitions.json impl_definitions.json} {
            if {![file exists [file join $d $f]]} continue
            dict for {- ovs} [readJson [file join $d $f]] {
                foreach ov $ovs {
                    dict set defs [dict get $ov ov_cimguiname] $ov
                }
            }
        }
        dict for {name t} [readJson [file join $d typedefs_dict.json]] {
            if {[string first "(*)" $t] > -1} {lappend callbacks $name}
        }
        set se [readJson [file join $d structs_and_enums.json]]
        lappend structs {*}[dict keys [dict get $se structs]]
        dict for {- values} [dict get $se enums] {
            foreach v $values {
                dict set enums [dict get $v name] [dict get $v calc_value]
            }
        }
    }

    set files {}
    foreach ns {imgui implot implot3d} {
        lappend files [file join $root src $ns funcs.tcl]
    }
    set records [loadDeclarations $files]

    set nerr 0
    foreach r $records {
        lassign $r name ret params file
        if {![dict exists $defs $name]} {
            puts "MISSING  $file : $name (not in definitions.json)"
            incr nerr
            continue
        }
        set d [dict get $defs $name]
        set cargs {}
        foreach a [dict get $d argsT] {
            if {[dict get $a type] eq "..."} continue
            lappend cargs [dict get $a name] [dict get $a type]
        }
        if {[lindex $params end] eq "..."} {set params [lrange $params 0 end-1]}

        set problems {}
        # (constructors, destructors : no return type)
        if {[dict exists $d constructor]} {
            set cret "[dict get $d stname]*"
        } else {
            set cret [dict getdef $d ret void]
        }
        if {![compatible $cret [list $ret] $structs $callbacks]} {
            lappend problems "return : C '$cret', cffi '$ret'"
        }
        if {[llength $cargs] != [llength $params]} {
            lappend problems "parameters : C [expr {[llength $cargs] / 2}],\
                cffi [expr {[llength $params] / 2}]"
        }
        foreach {cn ct} $cargs {tn tt} $params {
            if {$cn eq "" || $tn eq ""} break
            if {![compatible $ct $tt $structs $callbacks]} {
                lappend problems "$tn : C '$ct', cffi '[lindex $tt 0]'"
            }
            set tdef [lsearch -inline -index 0 [lrange $tt 1 end] default]
            if {[llength $tdef] && [dict exists $d defaults $cn]
                && ![dict exists $checkignore $name $tn]
            } {
                set cdef [dict get $d defaults $cn]
                if {![sameDefault $cdef [lindex $tdef 1] $enums]} {
                    lappend problems "$tn : default C '$cdef', cffi '[lindex $tdef 1]'"
                }
            }
        }
        if {[llength $problems]} {
            puts "CHANGED  $file : $name"
            puts "         C : $cret $name[dict get $d argsoriginal]"
            foreach p $problems {puts "         - $p"}
            incr nerr
        }
    }
    puts "[llength $records] functions checked, $nerr difference(s)."
    return $nerr
}

if {"-check" in $argv} {
    exit [expr {[::gen::check] > 0}]
}
::gen::main
