# Copyright (c) 2022-2026 Nicolas ROBERT.
# Distributed under MIT license. Please see LICENSE for details.
#
# This file is generated by generator/generate.tcl, do not edit by hand.

namespace eval ::implot {
    cffi::Struct create ImPlotAlignmentData {
        Vertical ImBool
        PadA     float
        PadB     float
        PadAMax  float
        PadBMax  float
    }

    cffi::Struct create ImPlotAnnotation {
        Pos        struct.::imgui::ImVec2
        Offset     struct.::imgui::ImVec2
        ColorBg    ImU32
        ColorFg    ImU32
        TextOffset int
        Clamp      ImBool
    }

    cffi::Struct create ImPlotAnnotationCollection {
        Annotations struct.::imgui::ImVector
        TextBuffer  struct.::imgui::ImGuiTextBuffer
        Size        int
    }

    cffi::Struct create ImPlotRange {
        Min double
        Max double
    }

    cffi::Struct create ImPlotTicker {
        Ticks      struct.::imgui::ImVector
        TextBuffer struct.::imgui::ImGuiTextBuffer
        MaxSize    struct.::imgui::ImVec2
        LateSize   struct.::imgui::ImVec2
        Levels     int
    }

    cffi::Struct create ImPlotTime {
        S  time_t
        Us int
    }

    cffi::Struct create ImPlotAxis {
        ID               ImGuiID
        Flags            ImPlotAxisFlags
        PreviousFlags    ImPlotAxisFlags
        Range            struct.ImPlotRange
        RangeCond        ImPlotCond
        Scale            ImPlotScale
        FitExtents       struct.ImPlotRange
        OrthoAxis        {pointer.ImPlotAxis nullok}
        ConstraintRange  struct.ImPlotRange
        ConstraintZoom   struct.ImPlotRange
        Ticker           struct.ImPlotTicker
        Formatter        {pointer nullok}
        FormatterData    {pointer nullok}
        FormatSpec       schar[16]
        Locator          {pointer nullok}
        LinkedMin        {pointer nullok}
        LinkedMax        {pointer nullok}
        PickerLevel      int
        PickerTimeMin    struct.ImPlotTime
        PickerTimeMax    struct.ImPlotTime
        TransformForward {pointer nullok}
        TransformInverse {pointer nullok}
        TransformData    {pointer nullok}
        PixelMin         float
        PixelMax         float
        ScaleMin         double
        ScaleMax         double
        ScaleToPixel     double
        Datum1           float
        Datum2           float
        HoverRect        struct.::imgui::ImRect
        LabelOffset      int
        ColorMaj         ImU32
        ColorMin         ImU32
        ColorTick        ImU32
        ColorTxt         ImU32
        ColorBg          ImU32
        ColorHov         ImU32
        ColorAct         ImU32
        ColorHiLi        ImU32
        Enabled          ImBool
        Vertical         ImBool
        FitThisFrame     ImBool
        HasRange         ImBool
        HasFormatSpec    ImBool
        ShowDefaultTicks ImBool
        Hovered          ImBool
        Held             ImBool
    }

    cffi::Struct create ImPlotColormapData {
        Keys         struct.::imgui::ImVector
        KeyCounts    struct.::imgui::ImVector
        KeyOffsets   struct.::imgui::ImVector
        Tables       struct.::imgui::ImVector
        TableSizes   struct.::imgui::ImVector
        TableOffsets struct.::imgui::ImVector
        Text         struct.::imgui::ImGuiTextBuffer
        TextOffsets  struct.::imgui::ImVector
        Quals        struct.::imgui::ImVector
        Map          struct.::imgui::ImGuiStorage
        Count        int
    }

    cffi::Struct create ImPlotTagCollection {
        Tags       struct.::imgui::ImVector
        TextBuffer struct.::imgui::ImGuiTextBuffer
        Size       int
    }

    cffi::Struct create ImPlotStyle {
        PlotDefaultSize    struct.::imgui::ImVec2
        PlotMinSize        struct.::imgui::ImVec2
        PlotBorderSize     float
        MinorAlpha         float
        MajorTickLen       struct.::imgui::ImVec2
        MinorTickLen       struct.::imgui::ImVec2
        MajorTickSize      struct.::imgui::ImVec2
        MinorTickSize      struct.::imgui::ImVec2
        MajorGridSize      struct.::imgui::ImVec2
        MinorGridSize      struct.::imgui::ImVec2
        PlotPadding        struct.::imgui::ImVec2
        LabelPadding       struct.::imgui::ImVec2
        LegendPadding      struct.::imgui::ImVec2
        LegendInnerPadding struct.::imgui::ImVec2
        LegendSpacing      struct.::imgui::ImVec2
        MousePosPadding    struct.::imgui::ImVec2
        AnnotationPadding  struct.::imgui::ImVec2
        FitPadding         struct.::imgui::ImVec2
        DigitalPadding     float
        DigitalSpacing     float
        Colors             struct.::imgui::ImVec4[16]
        Colormap           ImPlotColormap
        UseLocalTime       ImBool
        UseISO8601         ImBool
        Use24HourClock     ImBool
    }

    cffi::Struct create ImPlotNextPlotData {
        RangeCond ImPlotCond[6]
        Range     struct.ImPlotRange[6]
        HasRange  ImBool[6]
        Fit       ImBool[6]
        LinkedMin {{pointer[6]} nullok}
        LinkedMax {{pointer[6]} nullok}
    }

    cffi::Struct create ImPlotSpec {
        LineColor        {struct.::imgui::ImVec4 {default {x 0 y 0 z 0 w -1}}}
        LineColors       {pointer nullok {default NULL}}
        LineWeight       {float {default 1.0}}
        FillColor        {struct.::imgui::ImVec4 {default {x 0 y 0 z 0 w -1}}}
        FillColors       {pointer nullok {default NULL}}
        FillAlpha        {float {default 1.0}}
        Marker           {ImPlotMarker {default ImPlotMarker_None}}
        MarkerSize       {float {default 4}}
        MarkerSizes      {pointer nullok {default NULL}}
        MarkerLineColor  {struct.::imgui::ImVec4 {default {x 0 y 0 z 0 w -1}}}
        MarkerLineColors {pointer nullok {default NULL}}
        MarkerFillColor  {struct.::imgui::ImVec4 {default {x 0 y 0 z 0 w -1}}}
        MarkerFillColors {pointer nullok {default NULL}}
        Size             {float {default 4}}
        Offset           {int {default 0}}
        Stride           {int {default -1}}
        Flags            {ImPlotSpecFlags bitmask {default 0}}
    }

    cffi::Struct create ImPlotNextItemData {
        Spec             struct.ImPlotSpec
        RenderLine       ImBool
        RenderFill       ImBool
        RenderMarkerLine ImBool
        RenderMarkerFill ImBool
        RenderMarkers    ImBool
        HasHidden        ImBool
        Hidden           ImBool
        HiddenCond       ImPlotCond
    }

    cffi::Struct create ImPlotInputMap {
        Pan           ::imgui::ImGuiMouseButton
        PanMod        int
        Fit           ::imgui::ImGuiMouseButton
        Select        ::imgui::ImGuiMouseButton
        SelectCancel  ::imgui::ImGuiMouseButton
        SelectMod     int
        SelectHorzMod int
        SelectVertMod int
        Menu          ::imgui::ImGuiMouseButton
        OverrideMod   int
        ZoomMod       int
        ZoomRate      float
    }

    cffi::Struct create ImPlotContext {
        Plots                 struct.::imgui::ImPool
        Subplots              struct.::imgui::ImPool
        CurrentPlot           {pointer.ImPlotPlot nullok}
        CurrentSubplot        {pointer.ImPlotSubplot nullok}
        CurrentItems          {pointer.ImPlotItemGroup nullok}
        CurrentItem           {pointer.ImPlotItem nullok}
        PreviousItem          {pointer.ImPlotItem nullok}
        CTicker               struct.ImPlotTicker
        Annotations           struct.ImPlotAnnotationCollection
        Tags                  struct.ImPlotTagCollection
        Style                 struct.ImPlotStyle
        ColorModifiers        struct.::imgui::ImVector
        StyleModifiers        struct.::imgui::ImVector
        ColormapData          struct.ImPlotColormapData
        ColormapModifiers     struct.::imgui::ImVector
        Tm                    struct.::imgui::tm
        TempDouble1           struct.::imgui::ImVector
        TempDouble2           struct.::imgui::ImVector
        TempInt1              struct.::imgui::ImVector
        DigitalPlotItemCnt    int
        DigitalPlotOffset     int
        NextPlotData          struct.ImPlotNextPlotData
        NextItemData          struct.ImPlotNextItemData
        InputMap              struct.ImPlotInputMap
        OpenContextThisFrame  ImBool
        MousePosStringBuilder struct.::imgui::ImGuiTextBuffer
        SortItems             {pointer.ImPlotItemGroup nullok}
        AlignmentData         struct.::imgui::ImPool
        CurrentAlignmentH     {pointer.ImPlotAlignmentData nullok}
        CurrentAlignmentV     {pointer.ImPlotAlignmentData nullok}
    }

    cffi::Struct create ImPlotDateTimeSpec {
        Date           ImPlotDateFmt
        Time           ImPlotTimeFmt
        UseISO8601     ImBool
        Use24HourClock ImBool
    }

    cffi::Struct create ImPlotItem {
        ID              ImGuiID
        Color           ImU32
        Marker          ImPlotMarker
        LegendHoverRect struct.::imgui::ImRect
        NameOffset      int
        Show            ImBool
        LegendHovered   ImBool
        SeenThisFrame   ImBool
    }

    cffi::Struct create ImPlotLegend {
        Flags            ImPlotLegendFlags
        PreviousFlags    ImPlotLegendFlags
        Location         ImPlotLocation
        PreviousLocation ImPlotLocation
        Scroll           struct.::imgui::ImVec2
        Indices          struct.::imgui::ImVector
        Labels           struct.::imgui::ImGuiTextBuffer
        Rect             struct.::imgui::ImRect
        RectClamped      struct.::imgui::ImRect
        Hovered          ImBool
        Held             ImBool
        CanGoInside      ImBool
    }

    cffi::Struct create ImPlotItemGroup {
        ID          ImGuiID
        Legend      struct.ImPlotLegend
        ItemPool    struct.::imgui::ImPool
        ColormapIdx int
        MarkerIdx   ImPlotMarker
    }

    cffi::Struct create ImPlotPlot {
        ID                ImGuiID
        Flags             ImPlotFlags
        PreviousFlags     ImPlotFlags
        MouseTextLocation ImPlotLocation
        MouseTextFlags    ImPlotMouseTextFlags
        Axes              struct.ImPlotAxis[6]
        TextBuffer        struct.::imgui::ImGuiTextBuffer
        Items             struct.ImPlotItemGroup
        CurrentX          ImAxis
        CurrentY          ImAxis
        FrameRect         struct.::imgui::ImRect
        CanvasRect        struct.::imgui::ImRect
        PlotRect          struct.::imgui::ImRect
        AxesRect          struct.::imgui::ImRect
        SelectRect        struct.::imgui::ImRect
        SelectStart       struct.::imgui::ImVec2
        TitleOffset       int
        JustCreated       ImBool
        Initialized       ImBool
        SetupLocked       ImBool
        FitThisFrame      ImBool
        Hovered           ImBool
        Held              ImBool
        Selecting         ImBool
        Selected          ImBool
        ContextLocked     ImBool
    }

    cffi::Struct create ImPlotPoint {
        x double
        y double
    }

    cffi::Struct create ImPlotPointError {
        X   double
        Y   double
        Neg double
        Pos double
    }

    cffi::Struct create ImPlotRect {
        X struct.ImPlotRange
        Y struct.ImPlotRange
    }

    cffi::Struct create ImPlotSubplot {
        ID               ImGuiID
        Flags            ImPlotSubplotFlags
        PreviousFlags    ImPlotSubplotFlags
        Items            struct.ImPlotItemGroup
        Rows             int
        Cols             int
        CurrentIdx       int
        FrameRect        struct.::imgui::ImRect
        GridRect         struct.::imgui::ImRect
        CellSize         struct.::imgui::ImVec2
        RowAlignmentData struct.::imgui::ImVector
        ColAlignmentData struct.::imgui::ImVector
        RowRatios        struct.::imgui::ImVector
        ColRatios        struct.::imgui::ImVector
        RowLinkData      struct.::imgui::ImVector
        ColLinkData      struct.::imgui::ImVector
        TempSizes        float[2]
        FrameHovered     ImBool
        HasTitle         ImBool
    }

    cffi::Struct create ImPlotTag {
        Axis       ImAxis
        Value      double
        ColorBg    ImU32
        ColorFg    ImU32
        TextOffset int
    }

    cffi::Struct create ImPlotTick {
        PlotPos    double
        PixelPos   float
        LabelSize  struct.::imgui::ImVec2
        TextOffset int
        Major      ImBool
        ShowLabel  ImBool
        Level      int
        Idx        int
    }

}
