# Copyright (c) 2022-2026 Nicolas ROBERT.
# Distributed under MIT license. Please see LICENSE for details.
#
# This file is generated by generator/generate.tcl, do not edit by hand.

cffi::alias define ImBitArrayPtr            pointer
cffi::alias define ImDrawCallback           pointer
cffi::alias define ImDrawIdx                ushort
cffi::alias define ImFileHandle             pointer
cffi::alias define ImFontAtlasRectId        int
cffi::alias define ImGuiContextHookCallback pointer
cffi::alias define ImGuiDemoMarkerCallback  pointer
cffi::alias define ImGuiErrorCallback       pointer
cffi::alias define ImGuiID                  uint
cffi::alias define ImGuiInputTextCallback   pointer
cffi::alias define ImGuiKeyChord            int
cffi::alias define ImGuiMemAllocFunc        pointer
cffi::alias define ImGuiMemFreeFunc         pointer
cffi::alias define ImGuiSizeCallback        pointer
cffi::alias define ImPoolIdx                int
cffi::alias define ImS8                     schar
cffi::alias define ImS16                    short
cffi::alias define ImS32                    int
cffi::alias define ImS64                    longlong
cffi::alias define ImU8                     uchar
cffi::alias define ImU16                    ushort
cffi::alias define ImU32                    uint
cffi::alias define ImU64                    ulonglong
cffi::alias define ImWchar16                ushort
cffi::alias define ImWchar32                uint
cffi::alias define ImGuiKeyRoutingIndex     ImS16
cffi::alias define ImGuiSelectionUserData   ImS64
cffi::alias define ImGuiTableColumnIdx      ImS16
cffi::alias define ImGuiTableDrawChannelIdx ImU16
cffi::alias define ImTextureID              ImU64
cffi::alias define ImWchar                  ImWchar16

# define bool as type for struct
cffi::alias define ImBool                   uchar
# define bool as type for function
cffi::alias define CIMGUI_BOOL              uchar
