# Copyright (c) 2022-2026 Nicolas ROBERT.
# Distributed under MIT license. Please see LICENSE for details.
#
# This file is generated by generator/generate.tcl, do not edit by hand.

namespace eval ::imgui {

    # 'struct tm' (C library) is used by ImPlotContext.
    if {$::tcl_platform(platform) eq "windows"} {
        cffi::Struct create tm {
            tm_sec int tm_min int tm_hour int tm_mday int tm_mon int
            tm_year int tm_wday int tm_yday int tm_isdst int
        }
    } else {
        cffi::Struct create tm {
            tm_sec int tm_min int tm_hour int tm_mday int tm_mon int
            tm_year int tm_wday int tm_yday int tm_isdst int
            tm_gmtoff long tm_zone pointer
        }
    }

    cffi::Struct create ImVector {
        Size     int
        Capacity int
        Data     {pointer nullok}
    }

    cffi::Struct create ImChunkStream {
        Buf struct.::imgui::ImVector
    }

    cffi::Struct create ImVec4 {
        x float
        y float
        z float
        w float
    }

    cffi::Struct create ImColor {
        Value struct.ImVec4
    }

    cffi::Struct create ImDrawChannel {
        _CmdBuffer struct.::imgui::ImVector
        _IdxBuffer struct.::imgui::ImVector
    }

    cffi::Struct create ImTextureRef {
        _TexData {pointer.ImTextureData nullok}
        _TexID   ImTextureID
    }

    cffi::Struct create ImDrawCmd {
        ClipRect               struct.ImVec4
        TexRef                 struct.ImTextureRef
        VtxOffset              uint
        IdxOffset              uint
        ElemCount              uint
        UserCallback           {pointer nullok}
        UserCallbackData       {pointer nullok}
        UserCallbackDataSize   int
        UserCallbackDataOffset int
    }

    cffi::Struct create ImDrawCmdHeader {
        ClipRect  struct.ImVec4
        TexRef    struct.ImTextureRef
        VtxOffset uint
    }

    cffi::Struct create ImVec2 {
        x float
        y float
    }

    cffi::Struct create ImDrawData {
        Valid            ImBool
        FrameCount       int
        TotalIdxCount    int
        TotalVtxCount    int
        CmdLists         struct.::imgui::ImVector
        DisplayPos       struct.ImVec2
        DisplaySize      struct.ImVec2
        FramebufferScale struct.ImVec2
        OwnerViewport    {pointer.ImGuiViewport nullok}
        Textures         {pointer nullok}
    }

    cffi::Struct create ImDrawListSplitter {
        _Current  int
        _Count    int
        _Channels struct.::imgui::ImVector
    }

    cffi::Struct create ImDrawList {
        CmdBuffer         struct.::imgui::ImVector
        IdxBuffer         struct.::imgui::ImVector
        VtxBuffer         struct.::imgui::ImVector
        Flags             ImDrawListFlags
        _VtxCurrentIdx    uint
        _Data             {pointer nullok}
        _VtxWritePtr      {pointer.ImDrawVert nullok}
        _IdxWritePtr      {pointer nullok}
        _Path             struct.::imgui::ImVector
        _CmdHeader        struct.ImDrawCmdHeader
        _Splitter         struct.ImDrawListSplitter
        _ClipRectStack    struct.::imgui::ImVector
        _TextureStack     struct.::imgui::ImVector
        _CallbacksDataBuf struct.::imgui::ImVector
        _FringeScale      float
        _OwnerName        {pointer nullok}
    }

    cffi::Struct create ImDrawVert {
        pos struct.ImVec2
        uv  struct.ImVec2
        col ImU32
    }

    cffi::Struct create ImGuiStorage {
        Data struct.::imgui::ImVector
    }

    cffi::Struct create ImFont {
        LastBaked                {pointer.ImFontBaked nullok}
        OwnerAtlas               {pointer.ImFontAtlas nullok}
        Flags                    ImFontFlags
        CurrentRasterizerDensity float
        FontId                   ImGuiID
        LegacySize               float
        Sources                  struct.::imgui::ImVector
        EllipsisChar             ImWchar
        FallbackChar             ImWchar
        Used8kPagesMap           ImU8[1]
        EllipsisAutoBake         ImBool
        RemapPairs               struct.ImGuiStorage
    }

    cffi::Struct create ImFontAtlas {
        Flags               ImFontAtlasFlags
        TexDesiredFormat    ImTextureFormat
        TexGlyphPadding     int
        TexMinWidth         int
        TexMinHeight        int
        TexMaxWidth         int
        TexMaxHeight        int
        UserData            {pointer nullok}
        TexRef              struct.ImTextureRef
        TexData             {pointer.ImTextureData nullok}
        TexList             struct.::imgui::ImVector
        Locked              ImBool
        RendererHasTextures ImBool
        TexIsBuilt          ImBool
        TexPixelsUseColors  ImBool
        TexUvScale          struct.ImVec2
        TexUvWhitePixel     struct.ImVec2
        Fonts               struct.::imgui::ImVector
        Sources             struct.::imgui::ImVector
        TexUvLines          struct.ImVec4[33]
        TexNextUniqueID     int
        FontNextUniqueID    int
        DrawListSharedDatas struct.::imgui::ImVector
        Builder             {pointer nullok}
        FontLoader          {pointer nullok}
        FontLoaderName      {pointer nullok}
        FontLoaderData      {pointer nullok}
        FontLoaderFlags     uint
        RefCount            int
        OwnerContext        {pointer nullok}
    }

    cffi::Struct create ImFontAtlasRect {
        x   ushort
        y   ushort
        w   ushort
        h   ushort
        uv0 struct.ImVec2
        uv1 struct.ImVec2
    }

    cffi::Struct create ImFontBaked {
        IndexAdvanceX                                                       struct.::imgui::ImVector
        FallbackAdvanceX                                                    float
        Size                                                                float
        RasterizerDensity                                                   float
        IndexLookup                                                         struct.::imgui::ImVector
        Glyphs                                                              struct.::imgui::ImVector
        FallbackGlyphIndex                                                  int
        Ascent                                                              float
        Descent                                                             float
        MetricsTotalSurface_WantDestroy_LoadNoFallback_LoadNoRenderOnLayout uint
        LastUsedFrame                                                       int
        BakedId                                                             ImGuiID
        OwnerFont                                                           {pointer.ImFont nullok}
        FontLoaderDatas                                                     {pointer nullok}
    }

    cffi::Struct create ImFontConfig {
        Name                 schar[40]
        FontData             {pointer nullok}
        FontDataSize         int
        FontDataOwnedByAtlas ImBool
        MergeMode            ImBool
        PixelSnapH           ImBool
        OversampleH          ImS8
        OversampleV          ImS8
        EllipsisChar         ImWchar
        SizePixels           float
        GlyphRanges          {pointer nullok}
        GlyphExcludeRanges   {pointer nullok}
        GlyphOffset          struct.ImVec2
        GlyphMinAdvanceX     float
        GlyphMaxAdvanceX     float
        GlyphExtraAdvanceX   float
        FontNo               ImU32
        FontLoaderFlags      uint
        RasterizerMultiply   float
        RasterizerDensity    float
        ExtraSizeScale       float
        Flags                ImFontFlags
        DstFont              {pointer.ImFont nullok}
        FontLoader           {pointer nullok}
        FontLoaderData       {pointer nullok}
    }

    cffi::Struct create ImFontGlyph {
        Colored_Visible_SourceIdx_Codepoint uint
        AdvanceX                            float
        X0                                  float
        Y0                                  float
        X1                                  float
        Y1                                  float
        U0                                  float
        V0                                  float
        U1                                  float
        V1                                  float
        PackId                              int
    }

    cffi::Struct create ImFontGlyphRangesBuilder {
        UsedChars struct.::imgui::ImVector
    }

    cffi::Struct create ImGuiInputTextCallbackData {
        Ctx            {pointer nullok}
        EventFlag      ImGuiInputTextFlags
        Flags          ImGuiInputTextFlags
        UserData       {pointer nullok}
        ID             ImGuiID
        EventKey       ImGuiKey
        EventChar      ImWchar
        EventActivated ImBool
        BufDirty       ImBool
        Buf            {pointer nullok}
        BufTextLen     int
        BufSize        int
        CursorPos      int
        SelectionStart int
        SelectionEnd   int
    }

    cffi::Struct create ImGuiKeyData {
        Down             ImBool
        DownDuration     float
        DownDurationPrev float
        AnalogValue      float
    }

    cffi::Struct create ImGuiIO {
        ConfigFlags                                   ImGuiConfigFlags
        BackendFlags                                  ImGuiBackendFlags
        DisplaySize                                   struct.ImVec2
        DisplayFramebufferScale                       struct.ImVec2
        DeltaTime                                     float
        IniSavingRate                                 float
        IniFilename                                   {pointer nullok}
        LogFilename                                   {pointer nullok}
        UserData                                      {pointer nullok}
        Fonts                                         {pointer.ImFontAtlas nullok}
        FontDefault                                   {pointer.ImFont nullok}
        FontAllowUserScaling                          ImBool
        ConfigNavSwapGamepadButtons                   ImBool
        ConfigNavMoveSetMousePos                      ImBool
        ConfigNavCaptureKeyboard                      ImBool
        ConfigNavEscapeClearFocusItem                 ImBool
        ConfigNavEscapeClearFocusWindow               ImBool
        ConfigNavCursorVisibleAuto                    ImBool
        ConfigNavCursorVisibleAlways                  ImBool
        ConfigMacOSXBehaviors                         ImBool
        ConfigInputTrickleEventQueue                  ImBool
        ConfigInputTextCursorBlink                    ImBool
        ConfigInputTextEnterKeepActive                ImBool
        ConfigColorEditFlags                          ImGuiColorEditFlags
        ConfigDragClickToInputText                    ImBool
        ConfigWindowsResizeFromEdges                  ImBool
        ConfigWindowsMoveFromTitleBarOnly             ImBool
        ConfigWindowsCopyContentsWithCtrlC            ImBool
        ConfigScrollbarScrollByPage                   ImBool
        ConfigIniSettingsSaveLastUsedDate             ImBool
        ConfigIniSettingsAutoDiscardMonths            int
        ConfigDebugIniSettings                        ImBool
        MouseDrawCursor                               ImBool
        ConfigMemoryCompactTimer                      float
        MouseDoubleClickTime                          float
        MouseDoubleClickMaxDist                       float
        MouseSingleClickDelay                         float
        MouseDragThreshold                            float
        KeyRepeatDelay                                float
        KeyRepeatRate                                 float
        ConfigErrorRecovery                           ImBool
        ConfigErrorRecoveryEnableAssert               ImBool
        ConfigErrorRecoveryEnableDebugLog             ImBool
        ConfigErrorRecoveryEnableTooltip              ImBool
        ConfigDebugIsDebuggerPresent                  ImBool
        ConfigDebugHighlightIdConflicts               ImBool
        ConfigDebugHighlightIdConflictsShowItemPicker ImBool
        ConfigDebugBeginReturnValueOnce               ImBool
        ConfigDebugBeginReturnValueLoop               ImBool
        ConfigDebugIgnoreFocusLoss                    ImBool
        BackendPlatformName                           {pointer nullok}
        BackendRendererName                           {pointer nullok}
        BackendPlatformUserData                       {pointer nullok}
        BackendRendererUserData                       {pointer nullok}
        BackendLanguageUserData                       {pointer nullok}
        WantCaptureMouse                              ImBool
        WantCaptureKeyboard                           ImBool
        WantTextInput                                 ImBool
        WantSetMousePos                               ImBool
        WantSaveIniSettings                           ImBool
        NavActive                                     ImBool
        NavVisible                                    ImBool
        Framerate                                     float
        MetricsRenderVertices                         int
        MetricsRenderIndices                          int
        MetricsRenderWindows                          int
        MetricsActiveWindows                          int
        MouseDelta                                    struct.ImVec2
        Ctx                                           {pointer nullok}
        MousePos                                      struct.ImVec2
        MouseDown                                     ImBool[5]
        MouseWheel                                    float
        MouseWheelH                                   float
        MouseSource                                   ImGuiMouseSource
        KeyCtrl                                       ImBool
        KeyShift                                      ImBool
        KeyAlt                                        ImBool
        KeySuper                                      ImBool
        KeyMods                                       ImGuiKeyChord
        KeysData                                      struct.ImGuiKeyData[155]
        WantCaptureMouseUnlessPopupClose              ImBool
        MousePosPrev                                  struct.ImVec2
        MouseClickedPos                               struct.ImVec2[5]
        MouseClickedTime                              double[5]
        MouseClicked                                  ImBool[5]
        MouseDoubleClicked                            ImBool[5]
        MouseClickedCount                             ImU16[5]
        MouseClickedLastCount                         ImU16[5]
        MouseReleased                                 ImBool[5]
        MouseReleasedTime                             double[5]
        MouseDownOwned                                ImBool[5]
        MouseDownOwnedUnlessPopupClose                ImBool[5]
        MouseWheelRequestAxisSwap                     ImBool
        MouseCtrlLeftAsRightClick                     ImBool
        MouseDownDuration                             float[5]
        MouseDownDurationPrev                         float[5]
        MouseDragMaxDistanceSqr                       float[5]
        PenPressure                                   float
        AppFocusLost                                  ImBool
        AppAcceptingEvents                            ImBool
        InputQueueSurrogate                           ImWchar16
        InputQueueCharacters                          struct.::imgui::ImVector
    }

    cffi::Struct create ImGuiListClipper {
        DisplayStart     int
        DisplayEnd       int
        UserIndex        int
        ItemsCount       int
        ItemsHeight      float
        Flags            ImGuiListClipperFlags
        StartPosY        double
        StartSeekOffsetY double
        Ctx              {pointer nullok}
        TempData         {pointer nullok}
    }

    cffi::Struct create ImGuiMultiSelectIO {
        Requests      struct.::imgui::ImVector
        RangeSrcItem  ImGuiSelectionUserData
        NavIdItem     ImGuiSelectionUserData
        NavIdSelected ImBool
        RangeSrcReset ImBool
        ItemsCount    int
    }

    cffi::Struct create ImGuiOnceUponAFrame {
        RefFrame int
    }

    cffi::Struct create ImGuiPayload {
        Data           {pointer nullok}
        DataSize       int
        SourceId       ImGuiID
        SourceParentId ImGuiID
        DataFrameCount int
        DataType       schar[33]
        Preview        ImBool
        Delivery       ImBool
    }

    cffi::Struct create ImGuiPlatformImeData {
        WantVisible     ImBool
        WantTextInput   ImBool
        InputPos        struct.ImVec2
        InputLineHeight float
        ViewportId      ImGuiID
    }

    cffi::Struct create ImGuiPlatformIO {
        Platform_GetClipboardTextFn    {pointer nullok}
        Platform_SetClipboardTextFn    {pointer nullok}
        Platform_ClipboardUserData     {pointer nullok}
        Platform_OpenInShellFn         {pointer nullok}
        Platform_OpenInShellUserData   {pointer nullok}
        Platform_SetImeDataFn          {pointer nullok}
        Platform_ImeUserData           {pointer nullok}
        Platform_LocaleDecimalPoint    ImWchar
        Platform_SessionDate           int
        Renderer_TextureMaxWidth       int
        Renderer_TextureMaxHeight      int
        Renderer_RenderState           {pointer nullok}
        DrawCallback_ResetRenderState  {pointer nullok}
        DrawCallback_SetSamplerLinear  {pointer nullok}
        DrawCallback_SetSamplerNearest {pointer nullok}
        Textures                       struct.::imgui::ImVector
    }

    cffi::Struct create ImGuiSelectionBasicStorage {
        Size                    int
        PreserveOrder           ImBool
        UserData                {pointer nullok}
        AdapterIndexToStorageId {pointer nullok}
        _SelectionOrder         int
        _Storage                struct.ImGuiStorage
    }

    cffi::Struct create ImGuiSelectionExternalStorage {
        UserData               {pointer nullok}
        AdapterSetItemSelected {pointer nullok}
    }

    cffi::Struct create ImGuiSelectionRequest {
        Type           ImGuiSelectionRequestType
        Selected       ImBool
        RangeDirection ImS8
        RangeFirstItem ImGuiSelectionUserData
        RangeLastItem  ImGuiSelectionUserData
    }

    cffi::Struct create ImGuiSizeCallbackData {
        UserData    {pointer nullok}
        Pos         struct.ImVec2
        CurrentSize struct.ImVec2
        DesiredSize struct.ImVec2
    }

    cffi::Union create ImGuiStoragePair_Union {
        val_i int
        val_f float
        val_p {pointer nullok}
    }

    cffi::Struct create ImGuiStoragePair {
        key ImGuiID
        u   union.ImGuiStoragePair_Union
    }

    cffi::Struct create ImGuiStyle {
        FontSizeBase                     float
        FontScaleMain                    float
        FontScaleDpi                     float
        Alpha                            float
        DisabledAlpha                    float
        WindowPadding                    struct.ImVec2
        WindowRounding                   float
        WindowBorderSize                 float
        WindowBorderHoverPadding         float
        WindowMinSize                    struct.ImVec2
        WindowTitleAlign                 struct.ImVec2
        WindowMenuButtonPosition         ImGuiDir
        ChildRounding                    float
        ChildBorderSize                  float
        PopupRounding                    float
        PopupBorderSize                  float
        FramePadding                     struct.ImVec2
        FrameRounding                    float
        FrameBorderSize                  float
        ItemSpacing                      struct.ImVec2
        ItemInnerSpacing                 struct.ImVec2
        CellPadding                      struct.ImVec2
        TouchExtraPadding                struct.ImVec2
        IndentSpacing                    float
        ColumnsMinSpacing                float
        ScrollbarSize                    float
        ScrollbarRounding                float
        ScrollbarPadding                 float
        GrabMinSize                      float
        GrabRounding                     float
        LogSliderDeadzone                float
        ImageRounding                    float
        ImageBorderSize                  float
        TabRounding                      float
        TabBorderSize                    float
        TabMinWidthBase                  float
        TabMinWidthShrink                float
        TabCloseButtonMinWidthSelected   float
        TabCloseButtonMinWidthUnselected float
        TabBarBorderSize                 float
        TabBarOverlineSize               float
        TableAngledHeadersAngle          float
        TableAngledHeadersTextAlign      struct.ImVec2
        TreeLinesFlags                   ImGuiTreeNodeFlags
        TreeLinesSize                    float
        TreeLinesRounding                float
        MenuItemRounding                 float
        SelectableRounding               float
        DragDropTargetRounding           float
        DragDropTargetBorderSize         float
        DragDropTargetPadding            float
        ColorMarkerSize                  float
        ColorButtonPosition              ImGuiDir
        ButtonTextAlign                  struct.ImVec2
        SelectableTextAlign              struct.ImVec2
        InputTextCursorSize              float
        SeparatorSize                    float
        SeparatorTextBorderSize          float
        SeparatorTextAlign               struct.ImVec2
        SeparatorTextPadding             struct.ImVec2
        DisplayWindowPadding             struct.ImVec2
        DisplaySafeAreaPadding           struct.ImVec2
        MouseCursorScale                 float
        AntiAliasedLines                 ImBool
        AntiAliasedLinesUseTex           ImBool
        AntiAliasedFill                  ImBool
        CurveTessellationTol             float
        CircleTessellationMaxError       float
        Colors                           struct.ImVec4[61]
        HoverStationaryDelay             float
        HoverDelayShort                  float
        HoverDelayNormal                 float
        HoverFlagsForTooltipMouse        ImGuiHoveredFlags
        HoverFlagsForTooltipNav          ImGuiHoveredFlags
        _MainScale                       float
        _NextFrameFontSizeBase           float
    }

    cffi::Struct create ImGuiTableColumnSortSpecs {
        ColumnUserID  ImGuiID
        ColumnIndex   ImS16
        SortOrder     ImS16
        SortDirection ImGuiSortDirection
    }

    cffi::Struct create ImGuiTableSortSpecs {
        Specs      {pointer.ImGuiTableColumnSortSpecs nullok}
        SpecsCount int
        SpecsDirty ImBool
    }

    cffi::Struct create ImGuiTextBuffer {
        Buf struct.::imgui::ImVector
    }

    cffi::Struct create ImGuiTextFilter {
        InputBuf  schar[256]
        Filters   struct.::imgui::ImVector
        CountGrep int
    }

    cffi::Struct create ImGuiTextRange {
        b {pointer nullok}
        e {pointer nullok}
    }

    cffi::Struct create ImGuiViewport {
        ID                ImGuiID
        Flags             ImGuiViewportFlags
        Pos               struct.ImVec2
        Size              struct.ImVec2
        FramebufferScale  struct.ImVec2
        WorkPos           struct.ImVec2
        WorkSize          struct.ImVec2
        PlatformHandle    {pointer nullok}
        PlatformHandleRaw {pointer nullok}
    }

    cffi::Struct create ImPool {
        Buf        struct.::imgui::ImVector
        Map        struct.::imgui::ImGuiStorage
        FreeIdx    ImPoolIdx
        AliveCount ImPoolIdx
    }

    cffi::Struct create ImRect {
        Min struct.ImVec2
        Max struct.ImVec2
    }

    cffi::Struct create ImSpan {
        Data    {pointer nullok}
        DataEnd {pointer nullok}
    }

    cffi::Struct create ImTextureRect {
        x ushort
        y ushort
        w ushort
        h ushort
    }

    cffi::Struct create ImTextureData {
        UniqueID             int
        Status               ImTextureStatus
        BackendUserData      {pointer nullok}
        QueueUserData        {pointer nullok}
        TexID                ImTextureID
        Format               ImTextureFormat
        Width                int
        Height               int
        BytesPerPixel        int
        Pixels               {pointer nullok}
        UsedRect             struct.ImTextureRect
        UpdateRect           struct.ImTextureRect
        Updates              struct.::imgui::ImVector
        UnusedFrames         int
        RefCount             ushort
        UseColors            ImBool
        WantDestroyNextFrame ImBool
    }

}
